### ISSUE TITLE
Syntax highlighting indentation issues

### ISSUE THREAD

**Issue by synic** [JanGuillermo/vue3-markdown-it#14]
I've noticed that the highlighter doesn't always indent properly. Here's a python snippet:

![python](http://synic.world/s/16b83909.png)

Here's an apacheconf snippet:

![apacheconf](http://synic.world/s/9eb52d3c.png)

These are both indented properly in the source. Do you know of a way to fix this?

**Comment by JanGuillermo** [comment]
Hi @synic,

Can you provide the snippet in text so I can try reproducing this issue? I suspect that one of the packages may be interfering with the indents.

**Comment by JanGuillermo** [comment]
Yep, I found the source of the issue - `dedent`. I'll be pushing a fix some time today. Sorry about the inconvenience!

**Comment by synic** [comment]
you are awesome. Thanks!

**Comment by JanGuillermo** [comment]
Hey, @synic. I fixed it in 1.0.2.

One note - I made some code changes related to CSS, which you can look at README.md

**Comment by synic** [comment]
Yup, works great. Thank you!
